# Generated by Django 6.0.5 on 2026-05-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coupon_valid_from_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
